# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(1076, 767)
        PlotWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_KE = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_KE.setChecked(True)
        self.radioButton_KE.setObjectName("radioButton_KE")
        self.buttonGroup = QtWidgets.QButtonGroup(PlotWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_KE)
        self.verticalLayout_3.addWidget(self.radioButton_KE)
        self.radioButton_PE = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_PE.setObjectName("radioButton_PE")
        self.buttonGroup.addButton(self.radioButton_PE)
        self.verticalLayout_3.addWidget(self.radioButton_PE)
        self.radioButton_TE = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_TE.setObjectName("radioButton_TE")
        self.buttonGroup.addButton(self.radioButton_TE)
        self.verticalLayout_3.addWidget(self.radioButton_TE)
        self.radioButton_drift = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_drift.setObjectName("radioButton_drift")
        self.buttonGroup.addButton(self.radioButton_drift)
        self.verticalLayout_3.addWidget(self.radioButton_drift)
        self.radioButton_T = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_T.setObjectName("radioButton_T")
        self.buttonGroup.addButton(self.radioButton_T)
        self.verticalLayout_3.addWidget(self.radioButton_T)
        self.radioButton_P = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_P.setObjectName("radioButton_P")
        self.buttonGroup.addButton(self.radioButton_P)
        self.verticalLayout_3.addWidget(self.radioButton_P)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_normal = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_normal.setChecked(True)
        self.radioButton_normal.setObjectName("radioButton_normal")
        self.buttonGroup_units = QtWidgets.QButtonGroup(PlotWindow)
        self.buttonGroup_units.setObjectName("buttonGroup_units")
        self.buttonGroup_units.addButton(self.radioButton_normal)
        self.verticalLayout_6.addWidget(self.radioButton_normal)
        self.radioButton_MKS = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_MKS.setObjectName("radioButton_MKS")
        self.buttonGroup_units.addButton(self.radioButton_MKS)
        self.verticalLayout_6.addWidget(self.radioButton_MKS)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(
            164,
            282,
            QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Expanding,
        )
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.plotVars = MplWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.plotVars.sizePolicy().hasHeightForWidth()
        )
        self.plotVars.setSizePolicy(sizePolicy)
        self.plotVars.setObjectName("plotVars")
        self.horizontalLayout_7.addWidget(self.plotVars)
        self.tabWidget.addTab(self.tab, "")
        self.g_r = QtWidgets.QWidget()
        self.g_r.setObjectName("g_r")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.g_r)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.g_r)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox.sizePolicy().hasHeightForWidth()
        )
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_dr = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_dr.sizePolicy().hasHeightForWidth()
        )
        self.label_dr.setSizePolicy(sizePolicy)
        self.label_dr.setObjectName("label_dr")
        self.horizontalLayout_5.addWidget(self.label_dr)
        self.doubleSpinBox_dr = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_dr.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons
        )
        self.doubleSpinBox_dr.setProperty("value", 0.01)
        self.doubleSpinBox_dr.setObjectName("doubleSpinBox_dr")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_dr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_start = QtWidgets.QLabel(self.groupBox)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_4.addWidget(self.label_start)
        self.spinBox_start = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_start.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons
        )
        self.spinBox_start.setObjectName("spinBox_start")
        self.horizontalLayout_4.addWidget(self.spinBox_start)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_stop = QtWidgets.QLabel(self.groupBox)
        self.label_stop.setObjectName("label_stop")
        self.horizontalLayout_3.addWidget(self.label_stop)
        self.spinBox_stop = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_stop.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons
        )
        self.spinBox_stop.setObjectName("spinBox_stop")
        self.horizontalLayout_3.addWidget(self.spinBox_stop)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_step = QtWidgets.QLabel(self.groupBox)
        self.label_step.setObjectName("label_step")
        self.horizontalLayout.addWidget(self.label_step)
        self.spinBox_step = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_step.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons
        )
        self.spinBox_step.setProperty("value", 1)
        self.spinBox_step.setObjectName("spinBox_step")
        self.horizontalLayout.addWidget(self.spinBox_step)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.pushButton_plot = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.verticalLayout_4.addWidget(self.pushButton_plot)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.plotG_r = MplWidget(self.g_r)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.plotG_r.sizePolicy().hasHeightForWidth()
        )
        self.plotG_r.setSizePolicy(sizePolicy)
        self.plotG_r.setObjectName("plotG_r")
        self.horizontalLayout_6.addWidget(self.plotG_r)
        self.tabWidget.addTab(self.g_r, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2.addWidget(self.frame)
        PlotWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PlotWindow)
        self.statusbar.setObjectName("statusbar")
        PlotWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "Plots"))
        self.groupBox_2.setTitle(_translate("PlotWindow", "Variable to plot"))
        self.radioButton_KE.setText(_translate("PlotWindow", "Kinetic energy"))
        self.radioButton_PE.setText(
            _translate("PlotWindow", "Potential energy")
        )
        self.radioButton_TE.setText(_translate("PlotWindow", "Total energy"))
        self.radioButton_drift.setText(
            _translate("PlotWindow", "Energy drift")
        )
        self.radioButton_T.setText(_translate("PlotWindow", "Temperature"))
        self.radioButton_P.setText(_translate("PlotWindow", "Pressure"))
        self.groupBox_3.setTitle(_translate("PlotWindow", "Units"))
        self.radioButton_normal.setText(_translate("PlotWindow", "Reduced"))
        self.radioButton_MKS.setText(_translate("PlotWindow", "MKS"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab),
            _translate("PlotWindow", "State variables"),
        )
        self.groupBox.setTitle(_translate("PlotWindow", "Options"))
        self.label_dr.setText(_translate("PlotWindow", "dr"))
        self.label_start.setText(_translate("PlotWindow", "Initial\n" "step"))
        self.label_stop.setText(_translate("PlotWindow", "Final\n" "step"))
        self.label_step.setText(_translate("PlotWindow", "Stepping"))
        self.pushButton_plot.setText(_translate("PlotWindow", "Plot g(r)"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.g_r), _translate("PlotWindow", "g(r)")
        )


from pymd.gui.view.ui.MplWidget import MplWidget
